title: AlmaLinux kernel images (vmlinuz)

start_url: https://vault.almalinux.org/
download_folder: vmlinuz-almalinux
group: almalinux

# kernel-core contains vmlinuz for both el8 and el9
file_patterns:
  - ^kernel-core-(?!6|7|8|9|debuginfo).*\.x86_64\.rpm$

jobs:
  - name: al8
    folder_patterns:
      - ^8\.
      - .*
      - x86_64
      - os
      - Packages

  - name: al9
    folder_patterns:
      - ^9\.
      - .*
      - x86_64
      - os
      - Packages
